# https://taskfile.dev

version: "3"

vars:
  README: README.md
  PREFIX: "!["
  DOMAIN: "](https://img.shields.io/badge/"
  STYLE: "?style=for-the-badge&logo="
  SUFFIX: "&logoColor=white)"
  SOURCE: src/skills.yaml

tasks:
  default:
    cmds:
      - echo '<p>&nbsp;<img align="center" src="https://readmestats.999857.xyz/api?username=shaoyanji&show_icons=true&locale=en&theme=tokyonight" alt="shaoyanji stats" /></p>' > {{.README}}
      - echo "" >> {{.README}}
      - echo "## ðŸ”¨ Languages & Frameworks & Skills â­ï¸:"  >>{{.README}}
      - echo "### Web Design & Development ðŸ’»:" >> {{.README}}
      - echo "#### ðŸ™ˆ - Frontend:" >> {{.README}}
      - echo "" >> {{.README}}
      - task category:frontend
      - echo "#### ðŸ™‰ - Backend:" >> {{.README}}
      - task category:backend
      - echo "#### ðŸ™Š - Database:" >> {{.README}}
      - task category:database
      - echo "#### ðŸµ - Hosting Services and Web Tools:" >> {{.README}}
      - task category:hosting
      - echo "### DevOps â™¾ï¸:" >> {{.README}}
      - task category:devops
      - echo "### Others:" >> {{.README}}
      - task category:others
      - echo "### IDEs and Tools ðŸ› :" >> {{.README}}
      - task category:ide
  category:*:
    vars:
      CATEG: "{{index .MATCH 0}}"
      SIZE:
        sh: yq '.{{.CATEG}}.[]|key' {{.SOURCE}}
    cmds:
      - for: { var: SIZE }
        cmd: echo "{{.PREFIX}}HTML{{.DOMAIN}}$(task skill:{{.CATEG}}:{{.ITEM}})-$(task color:{{.CATEG}}:{{.ITEM}}){{.STYLE}}$(task skill:{{.CATEG}}:{{.ITEM}}){{.SUFFIX}}" >> {{.README}}

  skill:*:*:
    vars:
      CATEG: "{{index .MATCH 0}}"
      INDEX: "{{index .MATCH 1}}"
    cmds:
      - yq '.{{.CATEG}}.{{.INDEX}}.[]|key' {{.SOURCE}}
      # - yq '.{{.CATEG}}.{{.INDEX}}.[]' {{.SOURCE}}

  color:*:*:
    vars:
      CATEG: "{{index .MATCH 0}}"
      INDEX: "{{index .MATCH 1}}"
    cmds:
      # - yq '.{{.CATEG}}.{{.INDEX}}.[]|key' {{.SOURCE}}
      - yq '.{{.CATEG}}.{{.INDEX}}.[]' {{.SOURCE}}
