# https://taskfile.dev

version: "3"

vars:
  README: README.md
  SOURCE: src/skills.yaml

tasks:
  gitpush:
    cmds:
      - git add . && git commit -m "updated README.md" && git push
  default:
    cmds:
      - ./compile_readme.sh
      - task gitpush
  compile:
    cmds:
      - ./compile_readme.sh
